name: Linter
on: pull_request
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
            - uses: xt0rted/markdownlint-problem-matcher@c17ca40d1376f60aba7e7d38a8674a3f22f7f5b0 # v1
            - name: "Run Markdown linter"
              uses: docker://index.docker.io/avtodev/markdown-lint@sha256:6aeedc2f49138ce7a1cd0adffc1b1c0321b841dc2102408967d9301c031949ee # v1
              with:
                  args: src/*.md
                
